development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock
  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin_test
  pool: 5
  username: rails
  password: rails
  socket: /var/run/mysqld/mysqld.sock
